### ISSUE TITLE
AutoMapper usage

### ISSUE THREAD

**Issue by bahmani00** [AccountGo/accountgo#11]
I've added AutoMapper for converting objects to each other so instead of 
var contact = new Core.Domain.Contact();
            contact.ContactType = Core.Domain.ContactTypes.Customer;
            contact.FirstName = model.FirstName;
            contact.MiddleName = model.MiddleName;
            contact.LastName = model.LastName;
            contact.IsActive = true;
            contact.CreatedBy = User.Identity.Name;
            contact.CreatedOn = DateTime.Now;
            contact.ModifiedBy = User.Identity.Name;
            contact.ModifiedOn = DateTime.Now;
            _salesService.SaveContact(contact);
I'll do it in one line
            var target = new Contact();
            Mapper.Map(model, target);

and for converting domain obj to model obj
model = Mapper.Map<ContactViewModel>(_salesService.GetContact(id));

it'll save tons of coding. I used Heroic.AutoMapper: 
https://github.com/MattHoneycutt/HeroicFramework/tree/master/Heroic.AutoMapper

**Comment by bahmani00** [comment]
Can I add this feature to the app?

**Comment by codemvp** [comment]
Hi Daniel,

How are you doing? you can just call me Marvs.

Thanks for your continued suggestions on improving the app.

Can I request you to fork and add your suggestions? Then I'll create a pull request from your fork.

For the automapper, I initially add a library called AutoMapper but I have not used it. However, AutoMapper is well known and stable framework so I would suggest if you can adapt this the better. I think it will not be a problem with you cause I believe whatever you did in Heroic.AutoMapper can also be done with AutoMapper (http://automapper.org/)

Btw, you can contact me directly through my email mvpsolution@gmail.com

Happy coding!

Cheers,
Marvs

**Comment by bahmani00** [comment]
Hi Marvs

I'm crazy about yr project and would love to learn mvc architecture and coding.

I dont have experience in teamwork project in github.com but as you said I did a Fork and I did a bug fix for Fix the Print buttons(https://github.com/codemvp/accountgo/issues/17) and commited my code you can revise and decide.

For AutoMapper: it's been a long time im using it and lots of professionals recommend it.
I will gradually incorporate it in AccountGo.

Happy  new yr
Daniel
