### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by devshadab92** [AccountGo/accountgo#113]
hey ...
can anyone explain me the balance Sheet logic , actually i'm working on asp.net based application, and following  this database structure , stuck in the get balance sheet.

**Comment by marvinvperez** [comment]
I will refer you to further reading here about balance sheet. https://www.investopedia.com/terms/b/balancesheet.asp

You just need to group account into  Assets, Liabilities, Shareholders' Equity (equity for short)

 Assets = Liabilities + Shareholders' Equity

**Comment by devshadab92** [comment]
> I will refer you to further reading here about balance sheet. https://www.investopedia.com/terms/b/balancesheet.asp
> 
> You just need to group account into Assets, Liabilities, Shareholders' Equity (equity for short)
> 
> Assets = Liabilities + Shareholders' Equity

Thanks
