### ISSUE TITLE
Getting error on Installation

### ISSUE THREAD

**Issue by srimansvk** [AccountGo/accountgo#118]
Can you any one help me on installation. I am unable to Build the software and install. Getting attached Error. 

![accountgo error](https://user-images.githubusercontent.com/47901674/53267748-2a1af880-36b2-11e9-8e4c-f9f6c6b393bb.png)

**Comment by marvinvperez** [comment]
This is fixed on commit 6488dc2925cb02a344170b59de65d1a305beab9a
Basically, you need to execute first in `npm install` in AccountGoWeb project. I added this is csproj to automatically run it on build.
