### ISSUE TITLE
Migrating to AngularJS 2.0

### ISSUE THREAD

**Issue by codemvp** [AccountGo/accountgo#19]
Open for discussions -

As angularjs 2.0 near to final release, we're considering to use this as the primary javascript framework. 
Initially, we'd like to stick with standard razor mvc. We love to hear suggestion/comments on using angularjs vs standard razor+jquery.

Cheers,

**Comment by codebangla** [comment]
I think AngularJS 1.x is good for the next 1 year.

**Comment by codemvp** [comment]
I mean if we are going to use angular we must start on version 2 once released. We'd like to eliminate the burden of migrating again from 1.x to 2.0 as version 2 is a complete rewrite.

**Comment by bahmani00** [comment]
Good call Marvs

**Comment by EricForgy** [comment]
Makes sense :+1:

**Comment by khennny** [comment]
I would love it.
