### ISSUE TITLE
Security Model

### ISSUE THREAD

**Issue by codemvp** [AccountGo/accountgo#20]
Implement custom security model. The default aspnet membership only be use for authentication, handling security roles/permissions/groups is customized. This will provide flexibility of using different identity providers.

Add UI to manage users permissions/roles.

Mock up screens

Roles List

View Users

Edit Permissions per Role

**Comment by EricForgy** [comment]
We are looking at [Azure AD B2C](https://azure.microsoft.com/en-us/services/active-directory-b2c/). It is still in preview though.
