### ISSUE TITLE
Azure AD B2C

### ISSUE THREAD

**Issue by EricForgy** [AccountGo/accountgo#26]
Since this is now migrated to Azure, it might be good to use Azure AD B2C for sign-up and sign-in.

Edit: Oops. Realized I already mentioned this in #20 . At least I am consistent :)

**Comment by codemvp** [comment]
The WebAngular project which will be the actual front-end and using angular is now using ADFS as the primary authentication. Converting  this to AD B2C would not that hard I assume.
