### ISSUE TITLE
Create Documentation

### ISSUE THREAD

**Issue by codemvp** [AccountGo/accountgo#4]
Update home page with mode details and how to.

**Comment by atulchaturvedi** [comment]
Did any started on documentation, do we have any draft version of documentation.

**Comment by codemvp** [comment]
Hi,
documentation has not yet started.
Draft of front-end here:
[http://accountgo-dev.cloudapp.net:8080/accountsreceivable/salesorders/form

**Comment by EricForgy** [comment]
Looks nice :+1:

**Comment by vivencio2** [comment]
I will try to update some part of the current documentation some of it are a bit misplaced based on my experience setting it up.

**Comment by codemvp** [comment]
Agree. It's also important documentation and guides always up to date.
