### ISSUE TITLE
Add new page

### ISSUE THREAD

**Issue by IrfanSamad** [AccountGo/accountgo#80]
I want to add new par for forget the password , add or edit Fiscal Years etc..
what is the easy and best procedure to that .

thanks

**Comment by codemvp** [comment]
Irfan, for add/edit "Fiscal Year" you can start this by adding a new menu
under "Organization Settings" (i.e. "Fiscal Years). Once the user click the
menu, a list page of fiscal years is displayed in grid. The you have "New"
and "View" link button above. Check on others page implementation.

For the change password, you can suggest your idea. I kinda see this to be
on a "Profile" page. But we don't have that yet.

**Comment by IrfanSamad** [comment]
Thanks for the answer, i add the new line in _Layout.chtml 
 <li>
                                
                                <a href="~/administration/FiscalYears">Fiscal Years</a>
                            </li>
now how can i create FiscalYear method in controller .. because you are using some other tolls got generate view and models?
one i complete this i will give you forget pass process 

thanks

**Comment by codemvp** [comment]
You may need to create new view and models. The usual mvc way.

**Comment by IrfanSamad** [comment]
yes! i am trying.. currently working on controller classes in api and AccountGoweb

**Comment by IrfanSamad** [comment]
Done

**Comment by marvinvperez** [comment]
Great! you can do pull request.
