### ISSUE TITLE
Page not working

### ISSUE THREAD

**Issue by IrfanSamad** [AccountGo/accountgo#81]
Some files are missing and an able to work on application , like unable to make new PO because (purchaseorder.chunk.js) is missing and unable to view ChartOf Account .. its blank page
how can i fixit?

thanks

**Comment by IrfanSamad** [comment]
any update?

**Comment by marvinvperez** [comment]
Hi did you follow the instructions in the readme?

**Comment by IrfanSamad** [comment]
Hi, yes follow the instructions (all db tables has been generated and created successfully) , i just get the blank page of purchase and sales related pages eg. Add Purchase Order have just two line:
<div id="divPurchaseOrder"></div>
<script src="~/scripts/purchasing/purchaseorder.chunk.js" type="text/javascript"></script>

i am unable to create new Purchase Order ,Sales Order etc..

is there any this i missed?

**Comment by jsoques** [comment]
Make sure to do step #8
![image](https://cloud.githubusercontent.com/assets/12414216/20570220/26d80476-b179-11e6-82a8-5fb75a61bbb3.png)

**Comment by IrfanSamad** [comment]
Hi, josques,
i did setp #8 , but i got the error and unable to run webpack scripts
 
![image](https://cloud.githubusercontent.com/assets/19147667/20598132/67f9a518-b269-11e6-9b4e-3350e58b5f3f.png)

**Comment by IrfanSamad** [comment]
still waiting for solution . any fixit?

**Comment by codemvp** [comment]
did you install webpack? step no. 4

**Comment by IrfanSamad** [comment]
Yes, i did some pages are working like 
![image](https://cloud.githubusercontent.com/assets/19147667/20640305/b666961e-b3fb-11e6-892c-1bdd97516de1.png)
Purchase Invoice are not working eg. 
![image](https://cloud.githubusercontent.com/assets/19147667/20640311/dd3f758a-b3fb-11e6-9761-0c695f6644b1.png)
Chart Of Accounts:
![image](https://cloud.githubusercontent.com/assets/19147667/20640315/1e7fe980-b3fc-11e6-961c-a518be4cf9bd.png)

**Comment by IrfanSamad** [comment]
any solutions?

**Comment by IrfanSamad** [comment]
i am waiting for the help .. i am unable to find solutions

**Comment by goiwebdev** [comment]
Hi Irfan,

I already update the fix in github. What I did is to set an height for the div and that's fix the issue I encounter it in quotations. But for the Create Invoice I'm still investigating the issue.

Here's the fix for the account code but you can pull this to our repo.

  <div id="accounts" class="ag-blue" style="height: 400px;"></div>

**Comment by goiwebdev** [comment]
Hi Irfan,

I don't know what happen with the new invoice and it's now working to me. What I did is to Isolate the PurchaseInvoice.tsx, remove the components one by one and try to rebuild one at a time (e.g. remove   ValidationErrors  , PurchaseInvoiceHeader ,PurchaseInvoiceLines ,PurchaseInvoiceTotals ,  SavePurchaseInvoiceButton , CancelPurchaseInvoiceButton ,  PostButton and retain EditButton and after that include the second, third , fourth ).

No Idea what's the exact issue on this but I also push it in our github.

**Comment by IrfanSamad** [comment]
Hi goiwebdev,
I already solved the issue my self , its JS files calling issue i jut put    <script src="~/scripts/vendor.bundle.js"></script>  in _Layout.chtml and remove <!DOCTYPE html> from the top
now all pages is working fine.
here is my JS list below
 <script src="https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.5/bluebird.min.js"></script>
    
    
    <script src="~/plugins/jquery/dist/jquery.min.js"></script>
    
    <script src="~/plugins/bootstrap/dist/js/bootstrap.min.js"></script>
    
    <script src="~/adminLTE/js/app.js"></script>
    
    <script src="~/plugins/ag-grid/dist/ag-grid.js?ignore=notused24"></script>

    
    <script src="~/adminLTE/js/bootstrap-datetimepicker.js"></script>

    <script src="~/scripts/vendor.bundle.js"></script>

**Comment by IrfanSamad** [comment]
with ASP Core the development time too long and more complex .. ReactJS .. Dome, Dto, Api .etc .. so all issue will resolved but takes time

**Comment by joaopedromago** [comment]
i've solved the problem, the webpack.config.js must be like this:
/// <binding BeforeBuild='Run - Development' />
var webpack = require('webpack');
var path = require('path');

var buildDir = path.resolve(__dirname, './wwwroot/scripts');
var scriptsDir = path.resolve(__dirname, './wwwroot/libs/tsxbuild');
//var scriptsDir = path.resolve(__dirname, './Scripts');

var config = {
    entry: {
        home: scriptsDir + '/home' + '/home',
        "sales/salesorder": scriptsDir + '/sales/salesorder',
        "quotations/salesquotation": scriptsDir + '/quotations/salesquotation',
        "sales/salesinvoice": scriptsDir + '/sales/salesinvoice',
        "purchasing/purchaseorder": scriptsDir + '/purchasing/purchaseorder',
        "purchasing/purchaseinvoice": scriptsDir + '/purchasing/purchaseinvoice',
        "financials/journalentry": scriptsDir + '/financials/journalentry',
        vendor: ['react', 'react-dom']
    },
    output: {
        path: buildDir,
        filename: '[name].chunk.js'
    },
    resolve: {
        extensions: ['.js', '.jsx', '.tsx']
    },
   // debug: true,
    devtool: 'source-map',
    //module: {
    //    loaders: [
    //      {
    //          test: /\.tsx$/,
    //          loader: 'ts-loader',
    //          exclude: /(node_modules)/
    //      }
    //    ]
    //},
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({ name: 'vendor', filename: 'vendor.bundle.js' })
    ],
    externals: {
        'Config': JSON.stringify(process.env.ENV === 'production' ?
            {
                apiUrl: "http://accountgo-dev-api.azurewebsites.net/"
            } :
            {
                apiUrl: "http://localhost:5000/"
            })
    }
};

module.exports = config;
