### ISSUE TITLE
1500 errors   in Vs2015

### ISSUE THREAD

**Issue by vanderr3** [AccountGo/accountgo#84]
Vs2015 professional update 3. 
I get 1499 errors like the following
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1002	The dependency Microsoft.Net.Http.Headers 1.0.0 in project Api does not support framework .NETFramework,Version=v4.6.2.	

I would like to solve this but that does not seem possible without spending months of research (time I have not got)

Can anybody point me in the right direction so I can quickly resolve this

**Comment by amansulaiman** [comment]
Try visual Studio 2017. Let me know what problems you are getting.  Try to paste all logs file

**Comment by imahar** [comment]
Severity	Code	Description	Project	Line	File	Suppression State
Error	TS2559	Build:Type 'Component<P, S>' has no properties in common with type 'ComponentLifecycle<P, S>'.	AccountGoWeb	162	D:\Examples\accountgo-master\accountgo-master\src\AccountGoWeb\typings\react\react.d.ts
