### ISSUE TITLE
Cannot find vendor.bundle.js and chunk.js files

### ISSUE THREAD

**Issue by cllyldrm** [AccountGo/accountgo#91]
Hi, 

I follow the instructions and everything is ok. But some of the pages i got this 2 error.

Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9921/scripts/vendor.bundle.js 

Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:9921/scripts/quotations/salesquotation.chunk.js 

How can i fix it ?

**Comment by joaopedromago** [comment]
Hello,
I'm with this same issue.. Have you solved it yet?

**Comment by joaopedromago** [comment]
i've got it. The webpack.config.js must be like this:
/// <binding BeforeBuild='Run - Development' />
var webpack = require('webpack');
var path = require('path');

var buildDir = path.resolve(__dirname, './wwwroot/scripts');
var scriptsDir = path.resolve(__dirname, './wwwroot/libs/tsxbuild');
//var scriptsDir = path.resolve(__dirname, './Scripts');

var config = {
    entry: {
        home: scriptsDir + '/home' + '/home',
        "sales/salesorder": scriptsDir + '/sales/salesorder',
        "quotations/salesquotation": scriptsDir + '/quotations/salesquotation',
        "sales/salesinvoice": scriptsDir + '/sales/salesinvoice',
        "purchasing/purchaseorder": scriptsDir + '/purchasing/purchaseorder',
        "purchasing/purchaseinvoice": scriptsDir + '/purchasing/purchaseinvoice',
        "financials/journalentry": scriptsDir + '/financials/journalentry',
        vendor: ['react', 'react-dom']
    },
    output: {
        path: buildDir,
        filename: '[name].chunk.js'
    },
    resolve: {
        extensions: ['.js', '.jsx', '.tsx']
    },
   // debug: true,
    devtool: 'source-map',
    //module: {
    //    loaders: [
    //      {
    //          test: /\.tsx$/,
    //          loader: 'ts-loader',
    //          exclude: /(node_modules)/
    //      }
    //    ]
    //},
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({ name: 'vendor', filename: 'vendor.bundle.js' })
    ],
    externals: {
        'Config': JSON.stringify(process.env.ENV === 'production' ?
            {
                apiUrl: "http://accountgo-dev-api.azurewebsites.net/"
            } :
            {
                apiUrl: "http://localhost:5000/"
            })
    }
};

module.exports = config;

**Comment by marvinvperez** [comment]
Hi,
The project is upgraded to dotnet core 2.1 and updated the instructions how to properly build and run. I will close this issue, feel free to reopen if you still encountering issues.
Thanks
