### ISSUE TITLE
Please check if your database is ready/published.: Could not load file or assembly 'System.Diagnostics.DiagnosticSource,

### ISSUE THREAD

**Issue by codebangla** [AccountGo/accountgo#92]
Hello,

I have followed the steps of the readme.me but have found problems in running AccountGo on Windows 10 using VS 2017.

Here is my AccountGoWeb.csproj
https://gist.github.com/codebangla/579b29948a5630d530f6c7f0f82b4c5c

I have attached a snapshot.

Any help would be much appreciatable. 

Please check if your database is ready/published.: Could not load file or assembly 'System.Diagnostics.DiagnosticSource,
![w1](https://user-images.githubusercontent.com/2529742/28265633-94fffbf4-6b12-11e7-9759-fe7d32a5e23c.PNG)
![wre](https://user-images.githubusercontent.com/2529742/28265640-9b44d46c-6b12-11e7-9b64-16be804ee002.PNG)

**Comment by lepstein2007** [comment]
I was able to fix this by downgrading all the projects to .NET Framework 4.5.2 ([Project] > Properties > Application tab > Target framework).

However, now I get the error "Please check if your database is ready/published.: One or more errors occurred." 

In the output window it reads: 
code:-32000
message:No script for id: 31
Exception thrown: 'System.AggregateException' in mscorlib.dll

**Comment by lepstein2007** [comment]
FYI, this issue is addressed here: https://github.com/AccountGo/accountgo/issues/86

**Comment by szoora** [comment]
Done everything but i still get 

> Please check if your database is ready/published.: One or more errors  occurred

![image](https://user-images.githubusercontent.com/10994696/31577069-a592c958-b110-11e7-89e7-07bc4e84aad7.png)
When loging in using default email and password, i get a blank page
![image](https://user-images.githubusercontent.com/10994696/31577101-0bbf3e50-b111-11e7-8791-694999a7db4a.png)
I successfully published the database to SQLServer2016 and using vs2017
Where did I go wrong?
