### ISSUE TITLE
Adding new rows - issue

### ISSUE THREAD

**Issue by BruneiProjects** [AccountGo/accountgo#95]
Hi,
When i try to add sales quotation or journal entry, the page is blank and not showing any fields.
When i look the .cshtml it is referring .tsx files in Script folder. I already installed Typescript, so what is the issue?
i attached the images too.
http://localhost:9921/quotations/addsalesquotation
http://localhost:9921/financials/addjournalentry

![image](https://user-images.githubusercontent.com/31334215/32822329-ee0d965c-ca12-11e7-8fda-cd923e1a1e95.png)

![image](https://user-images.githubusercontent.com/31334215/32822344-08efe70e-ca13-11e7-8588-9eac4802f633.png)

**Comment by marvinvperez** [comment]
Have you tried to run the webpack? Your wwwroot should have scripts folder. It's the output when you run webpack.
<img width="637" alt="screen shot 2018-02-18 at 12 33 06 pm" src="https://user-images.githubusercontent.com/17961526/36348319-01e9e81c-14a8-11e8-90c8-8b500c82c14d.png">
