### ISSUE TITLE
illegal characters in path -InitializeChartOfAccountsAndAccountClasses 

### ISSUE THREAD

**Issue by Daffyydd** [AccountGo/accountgo#97]
Hey Team,

Am using VS 2017 and Window 10 and am not able to Initialize initial data (COA). 

Am getting Illegal Character in Path when running the code below

 string whole_file = System.IO.File.ReadAllText(filename);

Anyone who knows how to solve this problem.

regards
David

**Comment by dantz15** [comment]
have you debug what is inside the filename variable?

**Comment by Daffyydd** [comment]
@dantz15 I have not changed anything since a cloned it. Just followed the instruction but cant proceed beyond there.

I have saved the file in another folder and referenced it and worked...

I think there is a problem with Resource Manager
